import{a as b,S as L,i as n}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const w="45015535-1baf0a26e6ef32c92247ee5f8",S="https://pixabay.com/api/";let i=1,u="";async function d(e){e!==u&&(i=1,u=e);try{const o=await b.get(S,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:15}});return i+=1,o.data}catch(o){throw new Error(`Failed to fetch images: ${o.message}`)}}let c;const f=document.querySelector(".load-more"),y=document.querySelector(".loading-indicator");function m(e){document.querySelector(".gallery");const o=e.map(t=>`
    <li class="item">
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="text"><b>Likes</b> ${t.likes}</p>
        <p class="text"><b>Views</b> ${t.views}</p>
        <p class="text"><b>Comments</b> ${t.comments}</p>
        <p class="text"><b>Downloads</b> ${t.downloads}</p>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",o),c?c.refresh():c=new L(".gallery a"),v(),$()}function q(){document.querySelector(".gallery").innerHTML=""}function E(){f.style.display="block"}function h(){f.style.display="none"}function g(){y.style.display="block"}function v(){y.style.display="none"}function $(){const{height:e}=document.querySelector(".item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const B=document.getElementById("search-form"),x=document.querySelector(".load-more");let p="";B.addEventListener("submit",async e=>{e.preventDefault();const o=e.currentTarget.query.value.trim();if(o===""){n.error({title:"Error",message:"Search query cannot be empty"});return}p=o,q(),g(),h();try{const t=await d(o);t.hits.length===0?n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(t.hits),t.totalHits>15&&E())}catch(t){n.error({title:"Error",message:t.message})}});x.addEventListener("click",async()=>{g();try{const e=await d(p);e.hits.length===0||e.hits.length<15?(h(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})):m(e.hits)}catch(e){n.error({title:"Error",message:e.message})}});
//# sourceMappingURL=commonHelpers.js.map
